import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> insertWordsToFirestore() async {
  final FirebaseFirestore firestore = FirebaseFirestore.instance;
  final CollectionReference words = firestore.collection('words');

  // Helper function to insert words from a list
  Future<void> insertWordList(List<String> englishList, List<String> arabicList, String category) async {
    // Insert English words
    for (String word in englishList) {
      await words.add({
        'word': word,
        'language': 'English',
        'category': category,
      });
    }

    // Insert Arabic words
    for (String word in arabicList) {
      await words.add({
        'word': word,
        'language': 'Arabic',
        'category': category,
      });
    }
  }
    List<String> placesEng = [
  "Airport",
  "Bank",
  "Hospital",
  "School",
  "Library",
  "Post Office",
  "Supermarket",
  "Police Station",
  "Fire Station",
  "Mall",
  "Park",
  "Museum",
  "Theater",
  "Zoo",
  "Cinema",
  "Bus Station",
  "Train Station",
  "Stadium",
  "Restaurant",
  "Café",
  "Beach",
  "Forest",
  "Mountain",
  "Desert",
  "River",
  "Lake",
  "Waterfall",
  "Island",
  "Cave",
  "Volcano",
  "Kitchen",
  "Bathroom",
  "Bedroom",
  "Living Room",
  "Garden",
  "Garage",
  "Balcony",
  "Attic",
  "Basement",
  "Dining Room",
  "Eiffel Tower",
  "Great Wall of China",
  "Pyramids",
  "Times Square",
  "Big Ben",
  "Taj Mahal",
  "Statue of Liberty",
  "Colosseum",
  "Mount Everest",
  "Burj Khalifa",
  "Gas Station",
  "Highway",
  "Border",
  "Tunnel",
  "Bridge",
  "Harbor",
  "Ferry",
  "Train",
  "Airplane",
  "Cruise Ship",
];

List<String> placesArabic = [
  "المطار",
  "البنك",
  "المستشفى",
  "المدرسة",
  "المكتبة",
  "مكتب البريد",
  "السوبر ماركت",
  "قسم الشرطة",
  "محطة الإطفاء",
  "المول",
  "الحديقة",
  "المتحف",
  "المسرح",
  "حديقة الحيوان",
  "السينما",
  "محطة الحافلات",
  "محطة القطار",
  "الملعب",
  "المطعم",
  "المقهى",
  "الشاطئ",
  "الغابة",
  "الجبل",
  "الصحراء",
  "النهر",
  "البحيرة",
  "الشلال",
  "الجزيرة",
  "الكهف",
  "البركان",
  "المطبخ",
  "الحمام",
  "غرفة النوم",
  "غرفة المعيشة",
  "الحديقة المنزلية",
  "الكراج",
  "الشرفة",
  "العلية",
  "القبو",
  "غرفة الطعام",
  "برج إيفل",
  "سور الصين العظيم",
  "الأهرامات",
  "تايمز سكوير",
  "بيغ بن",
  "تاج محل",
  "تمثال الحرية",
  "الكولوسيوم",
  "قمة إيفرست",
  "برج خليفة",
  "محطة الوقود",
  "الطريق السريع",
  "الحدود",
  "النفق",
  "الجسر",
  "الميناء",
  "العبّارة",
  "القطار",
  "الطائرة",
  "سفينة الرحلات",
];
List<String> peopleEng = [
  "Doctor",
  "Teacher",
  "Engineer",
  "Pilot",
  "Chef",
  "Waiter",
  "Police Officer",
  "Firefighter",
  "Nurse",
  "Dentist",
  "Farmer",
  "Soldier",
  "Scientist",
  "Actor",
  "Singer",
  "Athlete",
  "Artist",
  "Photographer",
  "Writer",
  "Journalist",
  "Judge",
  "Lawyer",
  "Driver",
  "Mechanic",
  "Plumber",
  "Electrician",
  "Carpenter",
  "Butcher",
  "Barber",
  "Tailor",
  "Cashier",
  "Cleaner",
  "Librarian",
  "Pharmacist",
  "Security Guard",
  "Receptionist",
  "Baker",
  "Delivery Man",
  "Businessman",
  "Businesswoman",
  "Coach",
  "Tour Guide",
  "Magician",
  "Dancer",
  "Painter",
  "Programmer",
  "Designer",
  "Student",
  "Principal",
  "King",
  "Queen",
  "Prince",
  "Princess",
  "Clown",
  "Thief",
  "Detective",
  "Baby",
  "Old Man",
  "Old Woman",
];

List<String> peopleArabic = [
  "طبيب",
  "معلم",
  "مهندس",
  "طيار",
  "طاهٍ",
  "نادل",
  "شرطي",
  "رجل إطفاء",
  "ممرضة",
  "طبيب أسنان",
  "مزارع",
  "جندي",
  "عالم",
  "ممثل",
  "مغني",
  "رياضي",
  "فنان",
  "مصور",
  "كاتب",
  "صحفي",
  "قاضٍ",
  "محامٍ",
  "سائق",
  "ميكانيكي",
  "سباك",
  "كهربائي",
  "نجار",
  "جزار",
  "حلاق",
  "خياط",
  "أمين صندوق",
  "عامل نظافة",
  "أمين مكتبة",
  "صيدلي",
  "حارس أمن",
  "موظف استقبال",
  "خباز",
  "رجل توصيل",
  "رجل أعمال",
  "سيدة أعمال",
  "مدرب",
  "دليل سياحي",
  "ساحر",
  "راقص",
  "رسام",
  "مبرمج",
  "مصمم",
  "طالب",
  "مدير مدرسة",
  "ملك",
  "ملكة",
  "أمير",
  "أميرة",
  "مهرج",
  "لص",
  "محقق",
  "رضيع",
  "رجل عجوز",
  "امرأة عجوز",
];
List<String> emotionsEng = [
  "Happy",
  "Sad",
  "Angry",
  "Excited",
  "Scared",
  "Surprised",
  "Confused",
  "Tired",
  "Bored",
  "Nervous",
  "Shy",
  "Lonely",
  "Jealous",
  "Embarrassed",
  "Frustrated",
  "Proud",
  "Hopeful",
  "Grateful",
  "Annoyed",
  "Calm",
  "Disappointed",
  "Afraid",
  "Satisfied",
  "Love",
  "Hate",
  "Guilty",
  "Ashamed",
  "Peaceful",
  "Curious",
  "Depressed",
  "Relieved",
  "Worried",
  "Content",
  "Anxious",
  "Envious",
  "Overwhelmed",
  "Terrified",
  "Amused",
  "Joyful",
  "Serious",
  "Suspicious",
  "Disgusted",
  "Surprised",
  "Disrespected",
  "Empowered",
  "Insecure",
  "Determined",
  "Optimistic",
  "Pessimistic",
  "Trusting",
  "Helpful",
  "Kind",
  "Friendly",
  "Fearful",
  "Doubtful",
  "Irritated",
  "Upset",
  "Touched",
  "Moved",
];

List<String> emotionsArabic = [
  "سعيد",
  "حزين",
  "غاضب",
  "متحمس",
  "خائف",
  "مندهش",
  "مرتبك",
  "متعب",
  "يشعر بالملل",
  "متوتر",
  "خجول",
  "وحيد",
  "غيور",
  "محرج",
  "محبط",
  "فخور",
  "مفعم بالأمل",
  "ممتن",
  "منزعج",
  "هادئ",
  "محبط",
  "خائف",
  "راضٍ",
  "حب",
  "كره",
  "يشعر بالذنب",
  "يشعر بالخجل",
  "يشعر بالسلام",
  "فضولي",
  "مكتئب",
  "مرتاح",
  "قلق",
  "قنوع",
  "قلق جدًا",
  "حسود",
  "مثقل بالمشاعر",
  "مرعوب",
  "مسلٍ",
  "مبتهج",
  "جاد",
  "مرتاب",
  "مشمئز",
  "مندهش",
  "يشعر بعدم الاحترام",
  "قوي",
  "غير واثق",
  "مصمم",
  "متفائل",
  "متشائم",
  "واثق بالآخرين",
  "معطاء",
  "طيب",
  "ودود",
  "خائف",
  "مرتاب",
  "منفعل",
  "منزعج",
  "متأثر",
  "متأثر عاطفياً",
];
List<String> technologyEng = [
  "Computer",
  "Laptop",
  "Smartphone",
  "Tablet",
  "Charger",
  "Headphones",
  "Microphone",
  "Camera",
  "Drone",
  "Smartwatch",
  "USB",
  "Hard Drive",
  "SSD",
  "Motherboard",
  "Processor",
  "Keyboard",
  "Mouse",
  "Monitor",
  "Printer",
  "Scanner",
  "Router",
  "Modem",
  "Wi-Fi",
  "Bluetooth",
  "Speaker",
  "Projector",
  "Remote Control",
  "Game Console",
  "Joystick",
  "VR Headset",
  "AR Glasses",
  "Smart TV",
  "Software",
  "App",
  "Operating System",
  "Browser",
  "Website",
  "Cloud",
  "Server",
  "Network",
  "Database",
  "Code",
  "Algorithm",
  "Program",
  "AI",
  "Machine Learning",
  "Robot",
  "Cybersecurity",
  "Firewall",
  "Hacker",
  "Bug",
  "Update",
  "Download",
  "Upload",
  "Streaming",
  "Data",
  "Signal",
  "Battery",
  "Technology",
  "Digital",
  "Analog",
  "Satellite",
  "Sensor",
  "Touchscreen",
  "Facial Recognition",
  "Fingerprint",
  "GPS",
  "NFC",
  "QR Code",
  "3D Printer",
  "Smart Home",
  "Smart Light",
  "Smart Lock",
  "Smart Fridge",
  "Electric Car",
  "Charging Station",
  "Robot Vacuum",
  "Encryption",
  "Code Editor",
  "Compiler",
  "Terminal",
  "HTML",
  "Wi-Fi Extender",
  "Power Bank",
  "E-book Reader",
  "Streaming Service"
];

List<String> technologyArabic = [
  "كمبيوتر",
  "لابتوب",
  "هاتف ذكي",
  "جهاز لوحي",
  "شاحن",
  "سماعات",
  "ميكروفون",
  "كاميرا",
  "طائرة بدون طيار",
  "ساعة ذكية",
  "يو إس بي",
  "قرص صلب",
  "قرص الحالة الصلبة",
  "اللوحة الأم",
  "المعالج",
  "لوحة مفاتيح",
  "فأرة",
  "شاشة",
  "طابعة",
  "ماسح ضوئي",
  "راوتر",
  "مودم",
  "واي فاي",
  "بلوتوث",
  "مكبر صوت",
  "جهاز عرض",
  "جهاز تحكم",
  "جهاز ألعاب",
  "عصا تحكم",
  "نظارة واقع افتراضي",
  "نظارات الواقع المعزز",
  "تلفاز ذكي",
  "برنامج",
  "تطبيق",
  "نظام تشغيل",
  "متصفح",
  "موقع إلكتروني",
  "سحابة",
  "خادم",
  "شبكة",
  "قاعدة بيانات",
  "كود",
  "خوارزمية",
  "برمجة",
  "ذكاء اصطناعي",
  "تعلم الآلة",
  "روبوت",
  "الأمن السيبراني",
  "جدار حماية",
  "هاكر",
  "خلل برمجي",
  "تحديث",
  "تنزيل",
  "رفع",
  "بث مباشر",
  "بيانات",
  "إشارة",
  "بطارية",
  "تكنولوجيا",
  "رقمي",
  "تماثلي",
  "قمر صناعي",
  "مستشعر",
  "شاشة لمس",
  "التعرف على الوجه",
  "بصمة الإصبع",
  "نظام تحديد المواقع",
  "اتصال قريب المدى",
  "رمز الاستجابة السريعة",
  "طابعة ثلاثية الأبعاد",
  "منزل ذكي",
  "إضاءة ذكية",
  "قفل ذكي",
  "ثلاجة ذكية",
  "سيارة كهربائية",
  "محطة شحن",
  "روبوت تنظيف",
  "تشفير",
  "محرر الأكواد",
  "مترجم برمجي",
  "الطرفية",
  "إتش تي إم إل",
  "موسع واي فاي",
  "بطارية متنقلة",
  "قارئ كتب إلكترونية",
  "خدمة بث"
];
List<String> artEng = [
  "Painting",
  "Drawing",
  "Sketch",
  "Sculpture",
  "Clay",
  "Canvas",
  "Brush",
  "Easel",
  "Palette",
  "Oil Paint",
  "Watercolor",
  "Acrylic",
  "Pencil",
  "Charcoal",
  "Pastel",
  "Ink",
  "Graffiti",
  "Street Art",
  "Digital Art",
  "Animation",
  "Illustration",
  "Collage",
  "Photography",
  "Film",
  "Cinema",
  "Director",
  "Actor",
  "Actress",
  "Theater",
  "Stage",
  "Performance",
  "Musical",
  "Opera",
  "Ballet",
  "Dance",
  "Choreography",
  "Costume",
  "Makeup",
  "Lighting",
  "Set Design",
  "Ceramics",
  "Mosaic",
  "Architecture",
  "Calligraphy",
  "Design",
  "Graphic Design",
  "Fashion",
  "Style",
  "Exhibition",
  "Gallery",
  "Museum",
  "Portrait",
  "Self-Portrait",
  "Still Life",
  "Landscape",
  "Abstract",
  "Modern Art",
  "Classic Art",
  "Cubism",
  "Surrealism",
  "Impressionism"
];

List<String> artArabic = [
  "رسم",
  "تخطيط",
  "سكتش",
  "نحت",
  "صلصال",
  "قماش رسم",
  "فرشاة",
  "حامل رسم",
  "لوحة الألوان",
  "ألوان زيتية",
  "ألوان مائية",
  "أكريليك",
  "قلم رصاص",
  "فحم",
  "باستيل",
  "حبر",
  "جرافيتي",
  "فن الشارع",
  "فن رقمي",
  "رسوم متحركة",
  "رسم توضيحي",
  "كولاج",
  "تصوير فوتوغرافي",
  "فيلم",
  "سينما",
  "مخرج",
  "ممثل",
  "ممثلة",
  "مسرح",
  "خشبة المسرح",
  "عرض مسرحي",
  "مسرحية غنائية",
  "أوبرا",
  "باليه",
  "رقص",
  "تصميم رقص",
  "زي",
  "مكياج",
  "إضاءة",
  "تصميم الديكور",
  "خزف",
  "فسيفساء",
  "هندسة معمارية",
  "خط عربي",
  "تصميم",
  "تصميم جرافيكي",
  "موضة",
  "أسلوب",
  "معرض",
  "صالة عرض",
  "متحف",
  "بورتريه",
  "بورتريه ذاتي",
  "طبيعة صامتة",
  "منظر طبيعي",
  "فن تجريدي",
  "فن حديث",
  "فن كلاسيكي",
  "تكعيبية",
  "سريالية",
  "انطباعية"
];
List<String> foodEng = [
  "Pizza", "Burger", "Pasta", "Rice", "Chicken", "Beef", "Lamb", "Fish", "Shrimp", "Crab",
  "Eggs", "Cheese", "Milk", "Yogurt", "Bread", "Butter", "Jam", "Honey", "Salt", "Pepper",
  "Onion", "Garlic", "Tomato", "Potato", "Carrot", "Cucumber", "Lettuce", "Spinach", "Corn", "Peas",
  "Beans", "Chickpeas", "Lentils", "Apple", "Banana", "Orange", "Grapes", "Mango", "Watermelon", "Strawberry",
  "Blueberry", "Pineapple", "Avocado", "Coconut", "Lemon", "Lime", "Date", "Fig", "Olive", "Raisin",
  "Nuts", "Almonds", "Walnuts", "Cashews", "Chocolate", "Ice Cream", "Cake", "Cookie", "Donut", "Croissant",
  "Coffee", "Tea", "Juice", "Soda", "Water", "Soup", "Salad", "Sausage", "Hotdog", "Kebab",
  "Falafel", "Shawarma", "Biryani", "Steak", "Taco", "Nachos", "Sushi", "Ramen", "Curry", "Noodles"
];

List<String> foodArabic = [
  "بيتزا", "برجر", "مكرونة", "أرز", "دجاج", "لحم بقر", "لحم غنم", "سمك", "جمبري", "سلطعون",
  "بيض", "جبن", "حليب", "زبادي", "خبز", "زبدة", "مربى", "عسل", "ملح", "فلفل",
  "بصل", "ثوم", "طماطم", "بطاطس", "جزر", "خيار", "خس", "سبانخ", "ذرة", "بازلاء",
  "فاصوليا", "حمص", "عدس", "تفاح", "موز", "برتقال", "عنب", "مانجو", "بطيخ", "فراولة",
  "توت", "أناناس", "أفوكادو", "جوز هند", "ليمون", "ليمون أخضر", "تمر", "تين", "زيتون", "زبيب",
  "مكسرات", "لوز", "جوز", "كاجو", "شوكولاتة", "آيس كريم", "كيك", "كوكي", "دونات", "كرواسون",
  "قهوة", "شاي", "عصير", "صودا", "ماء", "شوربة", "سلطة", "سجق", "هوت دوج", "كباب",
  "فلافل", "شاورما", "برياني", "ستيك", "تاكو", "ناتشوز", "سوشي", "رامين", "كاري", "نودلز"
];
List<String> toolsEng = [
  "Hammer", "Screwdriver", "Wrench", "Pliers", "Drill", "Saw", "Tape Measure", "Level", "Chisel", "Utility Knife",
  "Screws", "Nails", "Bolts", "Glue", "Paintbrush", "Roller", "Sander", "Ladder", "Wheelbarrow", "Shovel",
  "Hoe", "Rake", "Axe", "Pickaxe", "Crowbar", "Clamps", "Toolbox", "Work Gloves", "Flashlight", "Helmet",
  "Safety Goggles", "Wire Cutter", "Voltage Tester", "Multimeter", "Soldering Iron", "Tape", "Stapler", "Scissors", "Welding Machine", "Grinder",
  "Socket", "Allen Key", "Hex Wrench", "File", "Vice", "Bench", "Tool Belt", "Paint Tray", "Screw Gun", "Stud Finder",
  "Laser Level", "Caliper", "Compass", "Trowel", "Putty Knife", "Heat Gun", "Hot Glue Gun", "Measuring Stick", "Brush", "Bucket",
  "Spade", "Anvil", "Jack", "Hydraulic Press", "Mallet", "Deburring Tool", "Planer", "Router", "Chainsaw", "Air Compressor",
  "Paint Sprayer", "Nail Gun", "Gloves", "Apron", "Clamp", "Sandpaper", "Drill Bit", "Pry Bar", "Caulking Gun", "Paint Scraper"
];

List<String> toolsArabic = [
  "مطرقة", "مفك", "مفتاح ربط", "كماشة", "مثقاب", "منشار", "شريط قياس", "ميزان", "إزميل", "سكين متعددة",
  "مسامير", "براغي", "صواميل", "غراء", "فرشاة طلاء", "رول طلاء", "آلة صنفرة", "سلم", "عربة يدوية", "مجرفة",
  "معول", "مشط زراعي", "فأس", "فأس حفر", "عتلة", "مشابك", "صندوق أدوات", "قفازات عمل", "مصباح يدوي", "خوذة",
  "نظارات أمان", "قاطعة أسلاك", "جهاز اختبار فولت", "جهاز قياس متعدد", "كاوية لحام", "شريط لاصق", "دباسة", "مقص", "آلة لحام", "مطحنة",
  "رأس مقبس", "مفتاح ألين", "مفتاح سداسي", "مبرد", "ملزمة", "منضدة", "حزام أدوات", "صينية طلاء", "مسدس براغي", "كاشف دعامات",
  "ميزان ليزري", "قدم قياس", "بوصلة", "مسطرين", "سكين معجون", "مسدس حراري", "مسدس غراء ساخن", "عصا قياس", "فرشاة", "دلو",
  "مجرفة صغيرة", "سندان", "رافعة", "مكبس هيدروليكي", "مطرقة مطاطية", "أداة تنعيم", "مُبَسْط", "مُجَوّف", "منشار كهربائي", "ضاغط هواء",
  "رشاش طلاء", "مسدس مسامير", "قفازات", "مريلة", "مشبك", "ورق صنفرة", "رأس مثقاب", "عتلة صغيرة", "مسدس سيليكون", "كاشط طلاء"
];
List<String> itemsEng = [
  "Phone", "Laptop", "Tablet", "Book", "Pen", "Pencil", "Notebook", "Bag", "Wallet", "Watch",
  "Key", "Sunglasses", "Shoes", "Jacket", "T-shirt", "Pants", "Hat", "Scarf", "Gloves", "Bottle",
  "Cup", "Mug", "Umbrella", "Charger", "Headphones", "Earbuds", "Camera", "Remote", "Television", "Toothbrush",
  "Towel", "Blanket", "Pillow", "Chair", "Table", "Couch", "Lamp", "Mirror", "Clock", "Fan",
  "Fridge", "Microwave", "Oven", "Toaster", "Backpack", "Comb", "Makeup", "Perfume", "Soap", "Shampoo",
  "Conditioner", "Deodorant", "Spoon", "Fork", "Knife", "Plate", "Bowl", "Ruler", "Calculator", "Calendar",
  "Mouse", "Keyboard", "USB", "Flash Drive", "Power Bank", "Speaker", "Tripod", "Notebook Paper", "Sticky Notes", "Glue Stick",
  "Eraser", "Highlighter", "Marker", "Stapler", "Tape", "Battery", "Fan Remote", "Game Controller", "Helmet", "Mask"
];

List<String> itemsArabic = [
  "هاتف", "لاب توب", "جهاز لوحي", "كتاب", "قلم", "قلم رصاص", "دفتر", "حقيبة", "محفظة", "ساعة",
  "مفتاح", "نظارات شمس", "حذاء", "جاكيت", "تيشيرت", "بنطلون", "قبعة", "وشاح", "قفازات", "زجاجة",
  "كوب", "مج", "مظلة", "شاحن", "سماعات رأس", "سماعات أذن", "كاميرا", "ريموت", "تلفاز", "فرشاة أسنان",
  "منشفة", "بطانية", "وسادة", "كرسي", "طاولة", "كنبة", "مصباح", "مرآة", "ساعة حائط", "مروحة",
  "ثلاجة", "ميكروويف", "فرن", "محمصة", "حقيبة ظهر", "مشط", "مكياج", "عطر", "صابون", "شامبو",
  "بلسم", "مزيل عرق", "ملعقة", "شوكة", "سكين", "طبق", "وعاء", "مسطرة", "آلة حاسبة", "تقويم",
  "فأرة", "لوحة مفاتيح", "يو إس بي", "فلاشة", "باور بانك", "سبيكر", "ترايبود", "ورق دفتر", "ملاحظات لاصقة", "لاصق",
  "ممحاة", "قلم تمييز", "ماركر", "دباسة", "شريط لاصق", "بطارية", "ريموت مروحة", "يد تحكم ألعاب", "خوذة", "قناع"
];
List<String> otherEng = [
  "Dream", "Night", "Day", "Luck", "Shadow", "Silence", "Sound", "Noise", "Whisper", "Light",
  "Darkness", "Wind", "Storm", "Rain", "Snow", "Fire", "Water", "Earth", "Sky", "Cloud",
  "Star", "Sun", "Moon", "Time", "Memory", "Hope", "Fear", "Joy", "Surprise", "Secret",
  "Magic", "Power", "Peace", "War", "Energy", "Love", "Hate", "Friendship", "Destiny", "Fate",
  "Truth", "Lie", "Gift", "Curse", "Journey", "Path", "Choice", "Freedom", "Prison", "Wish",
  "Game", "Chance", "Coin", "Signal", "Flash", "Mirror", "Trap", "Puzzle", "Code", "Map"
];

List<String> otherArabic = [
  "حلم", "ليل", "نهار", "حظ", "ظل", "صمت", "صوت", "ضوضاء", "همسة", "ضوء",
  "ظلام", "ريح", "عاصفة", "مطر", "ثلج", "نار", "ماء", "أرض", "سماء", "سحابة",
  "نجم", "شمس", "قمر", "وقت", "ذكرى", "أمل", "خوف", "فرح", "مفاجأة", "سر",
  "سحر", "قوة", "سلام", "حرب", "طاقة", "حب", "كراهية", "صداقة", "قدر", "مصير",
  "حقيقة", "كذبة", "هدية", "لعنة", "رحلة", "طريق", "خيار", "حرية", "سجن", "أمنية",
  "لعبة", "فرصة", "عملة", "إشارة", "وميض", "مرآة", "فخ", "لغز", "رمز", "خريطة"
];

    
  // Insert all word categories
  try {
    await insertWordList(placesEng, placesArabic, 'places');
    await insertWordList(peopleEng, peopleArabic, 'people');
    await insertWordList(emotionsEng, emotionsArabic, 'emotions');
    await insertWordList(technologyEng, technologyArabic, 'technology');
    await insertWordList(artEng, artArabic, 'art');
    await insertWordList(foodEng, foodArabic, 'food');
    await insertWordList(toolsEng, toolsArabic, 'tools');
    await insertWordList(itemsEng, itemsArabic, 'items');
    await insertWordList(otherEng, otherArabic, 'other');
    
    // ignore: avoid_print
    print('Successfully inserted all words into Firestore');
  } catch (e) {
    // ignore: avoid_print
    print('Error inserting words: $e');
  }
} 